services:
  - type: web
    name: quziar.github.io
    runtime: python
    repo: https://github.com/quziar/quziar.github.io
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    postDeployCommand: bash sync_databases.sh
version: "1"
